"""The two configurations that ran in CI, with 1 worker and with 5.

With 1 worker the simulation must reproduce the measured CI jobs exactly:
that checks the data and the model of a container. With 5 workers it
estimates how the same splits behave when Playwright runs 5 workers per
container, as production did.

Writes results/configurations.md.
"""
from pathlib import Path

from ci_split.data import configuration
from ci_split.playwright_sim import pipeline

OUT = Path(__file__).resolve().parents[1] / "results" / "configurations.md"


def main():
    rows = []
    for name, label in (("by-module", "One container per module"), ("balanced", "Balanced split (7 containers)")):
        containers, setups = configuration(name)
        for workers in (1, 5):
            time, cost, _ = pipeline(containers, setups, workers)
            rows.append((label, workers, time, cost))
    base = {w: (t, c) for label, w, t, c in rows if label.startswith("One")}
    lines = [
        "# The two configurations that ran in CI",
        "",
        "Generated by `scripts/compare_configurations.py`. Minutes per pipeline run; cost in USD per run.",
        "",
        "| Configuration | Workers per container | Pipeline (min) | Cost (USD) | Time vs by module | Cost vs by module |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for label, w, t, c in rows:
        bt, bc = base[w]
        lines.append(f"| {label} | {w} | {t:.2f} | {c:.2f} | {100 * (t / bt - 1):+.1f}% | {100 * (c / bc - 1):+.1f}% |")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(OUT.read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
