"""How many containers the pipeline needs with 5 workers each.

For 2 to 7 containers: solve the MILP, improve the split under
Playwright's file-order scheduling, and report pipeline time and cost
against the balanced split that ran in production. Every container's
setup is the average measured setup.

Writes results/containers.md and results/splits/<n>-containers.txt.
The solver has a time limit, so another run may find a different split
with the same or a very close time.
"""
from pathlib import Path
from statistics import mean

from ci_split.data import all_specs, configuration
from ci_split.model import floor, solve
from ci_split.playwright_sim import USD_PER_CONTAINER_MINUTE, pipeline
from ci_split.search import improve

WORKERS = 5
RESULTS = Path(__file__).resolve().parents[1] / "results"


def main():
    containers, setups = configuration("by-module")
    specs = all_specs(containers)
    setup = mean(setups.values())
    ref_time, ref_cost, _ = pipeline(*configuration("balanced"), WORKERS)

    lines = [
        f"# Containers against cost, {WORKERS} workers per container",
        "",
        "Generated by `scripts/containers_vs_cost.py`. Compared with the balanced split that ran in production "
        f"(7 containers, {WORKERS} workers): {ref_time:.2f} minutes and {ref_cost:.2f} USD per run.",
        "",
        f"Setup per container: {setup:.2f} min (average measured). "
        f"No split can finish before {floor(specs, setup):.2f} min: the setup plus the longest file of a suite.",
        "",
        "| Containers | Model (min) | Pipeline (min) | Cost (USD) | Time vs production | Cost vs production |",
        "|---:|---:|---:|---:|---:|---:|",
    ]
    (RESULTS / "splits").mkdir(parents=True, exist_ok=True)
    for n in range(2, 8):
        _, model_time, split = solve(specs, n, WORKERS, setup)
        split, (time, billed) = improve(specs, split, setup, WORKERS)
        cost = USD_PER_CONTAINER_MINUTE * billed
        lines.append(
            f"| {n} | {model_time:.2f} | {time:.2f} | {cost:.2f} | {100 * (time / ref_time - 1):+.1f}% | {100 * (cost / ref_cost - 1):+.1f}% |"
        )
        with open(RESULTS / "splits" / f"{n}-containers.txt", "w", encoding="utf-8") as f:
            for c, names in sorted(split.items()):
                f.write(f"# container {c + 1}\n" + "".join(f"src/tests/{s}\n" for s in names) + "\n")
    (RESULTS / "containers.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print((RESULTS / "containers.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
